config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/breweries", to: "breweries#index"
  get "/breweries/new", to: "breweries#new"
  post "/breweries", to: "breweries#create"
  get "/breweries/:id", to: "breweries#show"
  get "/breweries/:id/edit", to: "breweries#edit"
  patch "/breweries/:id", to: "breweries#update"
  delete "/breweries/:id", to: "breweries#destroy"

  get "/breweries/:brewery_id/beers", to: "breweries/beers#index"
  get "/breweries/:brewery_id/beers/new", to: "breweries/beers#new"
  post "/breweries/:brewery_id/beers", to: "breweries/beers#create"

  get "/beers", to: "beers#index"
  get "/beers/:id", to: "beers#show"
  get "/beers/:id/edit", to: "beers#edit"
  patch "/beers/:id", to: "beers#update"
  delete "/beers/:id", to: "beers#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :brewery

  def self.fermentation_completed
    where(fermentation_completed: true)
  end

  def self.exact_match_search(query)
    where(name: query)
  end

  def self.partial_match_search(query)
    where("name like ?", "%#{query}%")
  end
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  has_many :beers, dependent: :destroy

  def self.sort_by_creation_date
    order(created_at: :desc)
  end

  def self.exact_match_search(query)
    where(name: query)
  end

  def self.partial_match_search(query)
    where("name like ?", "%#{query}%")
  end

  def count_beers
    beers.count
  end

  def beers_over_ibu(input_ibu)
    beers.where("ibu > #{input_ibu}")
  end

  def beers_sorted_by_name
    beers.order(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers = get_beers
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def edit
    @beer = Beer.find(params[:id])
  end

  def update
    @beer = Beer.find(params[:id])
    @beer.update(beer_params)
    redirect_to "/beers/#{@beer.id}"
  end

  def destroy
    Beer.destroy(params[:id])
    redirect_to '/beers'
  end

  private
  def beer_params
    params.require(:beer).permit(:name, :style, :abv, :ibu, :fermentation_completed)
  end

  def get_beers
    if params[:query]
      Beer.exact_match_search(params[:query])
    elsif params[:fuzzy_query]
      Beer.partial_match_search(params[:fuzzy_query])
    else
      Beer.fermentation_completed
    end
  end
end

app/controllers/breweries/beers_controller.rb
class Breweries::BeersController < ApplicationController
  def index
    @brewery = Brewery.find(params[:brewery_id])
    @beers = get_beers
  end

  def new
    @brewery = Brewery.find(params[:brewery_id])
    @beer = Beer.new
  end

  def create
    @brewery = Brewery.find(params[:brewery_id])
    @brewery.beers.create(beer_params)
    redirect_to "/breweries/#{@brewery.id}/beers"
  end

  private
  def beer_params
    params.require(:beer).permit(:name, :style, :abv, :ibu, :fermentation_completed)
  end

  def get_beers
    if !params[:ibu].nil?
      @brewery.beers_over_ibu(params[:ibu])
    elsif params[:sort] == "AZ"
      @brewery.beers_sorted_by_name
    else
      @brewery.beers
    end
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  def index
    @breweries = get_breweries
  end

  def new
    @brewery = Brewery.new
  end

  def create
    Brewery.create(brewery_params)
    redirect_to '/breweries'
  end

  def show
    @brewery = Brewery.find(params[:id])
    @count = @brewery.count_beers
  end

  def edit
    @brewery = Brewery.find(params[:id])
  end

  def update
    @brewery = Brewery.find(params[:id])
    @brewery.update(brewery_params)
    redirect_to "/breweries/#{@brewery.id}"
  end

  def destroy
    Brewery.destroy(params[:id])
    redirect_to "/breweries"
  end

  private
  def brewery_params
    params.require(:brewery).permit(:name, :city, :tanks, :has_license)
  end

  def get_breweries
    if params[:query]
      Brewery.exact_match_search(params[:query])
    elsif params[:fuzzy_query]
      Brewery.partial_match_search(params[:fuzzy_query])
    else
      Brewery.sort_by_creation_date
    end
  end
end

app/controllers/brewery_beers_controller.rb
class BreweryBeersController < ApplicationController
  def index
    @brewery = Brewery.find(params[:brewery_id])
    @beers = sort_beers
  end

  def new
    @brewery = Brewery.find(params[:brewery_id])
    @beer = Beer.new
  end

  def create
    @brewery = Brewery.find(params[:brewery_id])
    @brewery.beers.create(beer_params)
    redirect_to "/breweries/#{@brewery.id}/beers"
  end

  private
  def beer_params
    params.require(:beer).permit(:name, :style, :abv, :ibu, :fermentation_completed)
  end

  def sort_beers
    if !params[:ibu].nil?
      @brewery.beers.where("ibu > #{params[:ibu]}")
    elsif params[:sort] == "AZ"
      @brewery.beers.order(:name)
    else
      @brewery.beers
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/edit.html.erb
<h1>Update Beer Details</h1>

<%= form_with model: @beer, url: "/beers/#{@beer.id}", method: :patch, local: true do |form| %>
  <%= form.label :name, "Name:" %>
  <%= form.text_field :name %>
  <%= form.label :style, "Style:" %>
  <%= form.text_field :style %>
  <%= form.label :ibu, "IBU:" %>
  <%= form.number_field :ibu %>
  <%= form.label :abv, "ABV:" %>
  <%= form.number_field :abv %>
  <%= form.label :fermentation_completed, "Fermentation Completed?" %>
  <%= form.check_box :fermentation_completed %>
  <%= form.submit "Save Changes" %>
<% end %>

app/views/beers/index.html.erb
<h1>All Beers</h1>

<%= render "shared/beer_details" %>

<div>
  <%= form_with url: "/beers", local: true, method: :get do |form| %>
    <%= form.label :query, "Filter Beers by Name:" %>
    <%= form.text_field :query %>
    <%= form.submit "Submit Exact Search" %>
  <% end %>
</div>

<div>
  <%= form_with url: "/beers", local: true, method: :get do |form| %>
    <%= form.label :fuzzy_query, "Filter Beers by Partial Name:" %>
    <%= form.text_field :fuzzy_query %>
    <%= form.submit "Submit Partial Search" %>
  <% end %>
</div>

app/views/beers/show.html.erb
<h1><%= @beer.name %></h1>
<p><b>Style:</b> <%= @beer.style %><p>
<p><b>Alcohol by Volume(ABV):</b> <%= @beer.abv%>%<p>
<p><b>Bitterness:</b> <%= @beer.ibu%> IBU<p>
<p><b>Fermentation Completed?</b> <%= @beer.fermentation_completed%><p>

<p><%= link_to 'Update This Beer', "/beers/#{@beer.id}/edit" %><p>
<p><%= link_to 'Delete This Beer', "/beers/#{@beer.id}", method: :delete %></p>

app/views/breweries/beers/index.html.erb
<h1><%= @brewery.name %></h1>

<%= render "shared/beer_details" %>

<p><%= link_to 'Create New Beer', "/breweries/#{@brewery.id}/beers/new" %></p>
<p><%= link_to 'Sort Beers A to Z', "/breweries/#{@brewery.id}/beers?sort=AZ" %></p>

<p><b>Show Only Beers with Bitterness (IBU) Over:</b></p>
<%= form_with url: "/breweries/#{@brewery.id}/beers", method: :get, local: true do |form| %>
  <%= form.number_field :ibu %>
  <%= form.submit 'Filter' %>
<% end %>

app/views/breweries/beers/new.html.erb
<h1>Create a New Beer</h1>

<%= form_with model: @beer, url: "/breweries/#{@brewery.id}/beers", method: :post, local: true do |form| %>
  <%= form.label :name, "Name:" %>
  <%= form.text_field :name %>
  <%= form.label :style, "Style:" %>
  <%= form.text_field :style %>
  <%= form.label :ibu, "IBU:" %>
  <%= form.number_field :ibu %>
  <%= form.label :abv, "ABV:" %>
  <%= form.number_field :abv %>
  <%= form.label :fermentation_completed, "Fermentation Completed?" %>
  <%= form.check_box :fermentation_completed %>
  <%= form.submit "Create Beer" %>
<% end %>

app/views/breweries/edit.html.erb
<h1>Update Brewery Details</h1>

<%= form_with model: @brewery, url: "/breweries/#{@brewery.id}", method: :patch, local: true do |form| %>
  <%= form.label :name, "Name:" %>
  <%= form.text_field :name %>
  <%= form.label :city, "City:" %>
  <%= form.text_field :city %>
  <%= form.label :tanks, "Number of Tanks:" %>
  <%= form.number_field :tanks %>
  <%= form.label :has_license, "Has License?" %>
  <%= form.check_box :has_license %>
  <%= form.submit "Save Changes" %>
<% end %>

app/views/breweries/index.html.erb
<h1>All Breweries</h1>

  <% @breweries.each do |brewery| %>
    <div id="brewery_details">
      <h3><%= brewery.name %></h3>
      <p><b>Created at:</b> <%= brewery.created_at %><p>
      <div id="edit_delete_brewery">
        <%= link_to "Edit #{brewery.name}", "/breweries/#{brewery.id}/edit" %>
        |
        <%= link_to "Delete #{brewery.name}", "/breweries/#{brewery.id}", method: :delete %>
      </div>
    </div>
  <% end %>

<p><b><%= link_to 'New Brewery', '/breweries/new' %></b></p>

<div>
  <%= form_with url: "/breweries", local: true, method: :get do |form| %>
    <%= form.label :query, "Filter Breweries by Name:" %>
    <%= form.text_field :query %>
    <%= form.submit "Submit Exact Search" %>
  <% end %>
</div>

<div>
  <%= form_with url: "/breweries", local: true, method: :get do |form| %>
    <%= form.label :fuzzy_query, "Filter Breweries by Partial Name:" %>
    <%= form.text_field :fuzzy_query %>
    <%= form.submit "Submit Partial Search" %>
  <% end %>
</div>

app/views/breweries/new.html.erb
<h1>Create a New Brewery</h1>

<%= form_with model: @brewery, url: "/breweries", method: :post, local: true do |form| %>
  <%= form.label :name, "Name:" %>
  <%= form.text_field :name %>
  <%= form.label :city, "City:" %>
  <%= form.text_field :city %>
  <%= form.label :tanks, "Number of Tanks:" %>
  <%= form.number_field :tanks %>
  <%= form.label :has_license, "Has License?" %>
  <%= form.check_box :has_license %>
  <%= form.submit "Create Brewery" %>
<% end %>

app/views/breweries/show.html.erb
<h1><%= @brewery.name %></h1>

<p><b>City:</b> <%= @brewery.city %><p>
<p><b>Number of Tanks:</b> <%= @brewery.tanks %><p>
<p><b>License Obtained?</b> <%= @brewery.has_license %><p>
<p><b>Beers:</b> <%= @count %><p>

<a href="/breweries/<%="#{@brewery.id}"%>/beers">All <%="#{@brewery.name}"%> Beers</a>

<p><%= link_to 'Update Brewery', "/breweries/#{@brewery.id}/edit" %></p>
<p><%= link_to "Delete #{@brewery.name}", "/breweries/#{@brewery.id}", method: :delete %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RelationalRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_beer_details.html.erb
<% @beers.each do |beer| %>
  <div id="beer_details">
    <h3><%= beer.name %></h3>
      <div id="edit_delete_beers">
        <%= link_to "Edit #{beer.name}", "/beers/#{beer.id}/edit" %>
        |
        <%= link_to "Delete #{beer.name}", "/beers/#{beer.id}", method: :delete %>
      </div>
    <p><b>Style:</b> <%= beer.style %><p>
    <p><b>Alcohol by Volume(ABV):</b> <%= beer.abv%>%<p>
    <p><b>Bitterness:</b> <%= beer.ibu%> IBU<p>
    <p><b>Fermentation Completed?</b> <%= beer.fermentation_completed%><p>
  </div>
<% end %>

app/views/shared/_header.html.erb
<p><%= link_to "See All Breweries", breweries_path %> | <%= link_to "See All Beers", beers_path %> </p>